### ISSUE TITLE
10 min to cuxfilter NVbug

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#449]
NVBUG: https://nvbugswb.nvidia.com/NvBugs5/swbug.aspx?bugid=3972341&cmtNo=

Possibly related to symlink changes.

```
[NbConvertApp] Converting notebook /rapids/notebooks/repos/cuxfilter/notebooks/10_minutes_to_cuxfilter.ipynb to script
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/jupyter_core/application.py", line 276, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    modified_date = datetime.datetime.fromtimestamp(os.path.getmtime(filename))
  File "/opt/conda/envs/rapids/lib/python3.9/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/rapids/notebooks/repos/cuxfilter/notebooks/10_minutes_to_cuxfilter.ipynb'
Running "ipython --colors=NoColor /tmp/tmp.X4H80NDomA.py" on Tue Feb  7 10:21:17 UTC 2023

--------------------------------------------------------------------------------

Please refer the attachment log file "rapids_test_v100_1gpu.log" for details.

Also, could reproduce this bug with T4, A100 GPU
```

**Comment by AjayThorve** [comment]
This was [fixed](https://github.com/rapidsai/cuxfilter/commit/a16a2bf21a8fd186efa044071d269be11e86b4aa) in v23.02:
